#!/usr/bin/perl

$args = "@ARGV";
#printf "\nmaking csv file $args";

system("rm -f *.csv *.html *.rds");


$der = "perl makederiv.perl ";
$check = "perl checkfreq.perl ";
$graph = "perl makegraphs.perl ";

for $f (@ARGV){
    $check = $check." $f/train*";
    $der = $der." $f/der*";
    $graph = $graph." $f/sum*";
}
#print($check);
$num = 14;

$f = $ARGV[1];
$f =~ s/^sim.+?[-]s[0-9][-]/stat/;

$onecommand = "$graph;$check;$der;";
print($onecommand);
system($onecommand);
system("Rscript -e \"library(knitr);require(markdown); knit('stat$num.Rmd');markdownToHTML('stat$num.md', 'stat$num.html') \" ");
sleep 1 while ( !(-e "stat$num.html") );
print("found stat$num.html");
system("cp stat$num.html $f.html");
$df = $ARGV[1];
system("cp *.csv *.rds *.html $df");

system("egrep '(Folder|<h2>|@@)' stat$num.html | perl -nle 's/<[^>]+?>//g;s/@@//g;s/Folder/\n/;print'>> laysummary");
system("tail -60 laysummary");
#system("cp stat5.html ERPs_DPM/");
